# Generated by Django 2.0.7 on 2018-08-14 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_centre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.TextField()),
                ('date', models.DateField()),
                ('slot', models.CharField(max_length=100)),
                ('sports_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_centre.SportsCentre')),
            ],
        ),
    ]
