# Generated by Django 2.0.7 on 2018-08-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_centre', '0003_auto_20180814_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportscentre',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
